channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - datalad
  - numpy=1.23
  - pip:
    - sphinx-gallery
    - sphinx_rtd_theme
    - numpydoc
    - MEArec>=1.7.1
    - hdbscan
    - numba
    - git+https://github.com/NeuralEnsemble/python-neo.git
    - git+https://github.com/SpikeInterface/probeinterface.git
    - git+https://github.com/SpikeInterface/spikeinterface.git#egg=spikeinterface[full,widgets]
