name: si_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy<2
  - scipy
  - joblib
  - tqdm
  - matplotlib
  - h5py
  - pandas
  - xarray
  - zarr
  - scikit-learn
  - hdbscan
  - networkx
  - pybind11
  - loky
  - numba
  - jupyter
  - pyqt=5
  - pyqtgraph
  - ipywidgets
  - ipympl
  - htop
  - cxx-compiler
  - libxcb
  - pip:
    - ephyviewer
    - MEArec
    - spikeinterface[full,widgets]
    - spikeinterface-gui
    - tridesclous
    - kilosort
