name: S3 NWB Test
on:
  pull_request:
    branches: [master]
    types: [synchronize, opened, reopened, ready_for_review]
jobs:
  build-and-test:
    name: Testing using ${{ matrix.os }} with ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: conda-forge
      - run: git fetch --prune --unshallow --tags
      - name: Install openblas
        run: sudo apt install libopenblas-dev liblapack-dev
      - name: Install pytest
        run: |
          python -m pip install -U pip  # Official recommended way
          pip install pytest
      - name: Install package
        run: |
          pip install -e .
          pip install pynwb
      # - name: Uninstall h5py
      #   run: pip uninstall -y h5py
      - name: Install h5py with ROS3 support
        run: |
#          conda install -c conda-forge "h5py>=3.2"
          python -c "import h5py; assert 'ros3' in h5py.registered_drivers(), f'ros3 suppport not available, failed to install'"
      - name: Install fsspec, aiohttp and requests
        run: pip install fsspec aiohttp requests
      - name: run tests
        run: pytest spikeinterface/extractors/tests/test_nwb_s3_extractor.py
