name: Test streaming extractors

on:
  pull_request:
    types: [synchronize, opened, reopened]
    branches:
      - main

concurrency:  # Cancel previous workflows on the same pull request
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-streaming-extractors:
    name: Testing using ${{ matrix.os }} with ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: conda-forge
      - run: git fetch --prune --unshallow --tags
      - name: Install openblas
        run: sudo apt install libopenblas-dev  # Necessary for ROS3 support
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
      - name: Module changes
        id: modules-changed
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == *"/nwbextractors.py" || $file == *"/iblstreamingrecording.py"* ]]; then
              echo "Streaming files changed changed"
              echo "STREAMING_CHANGED=true" >> $GITHUB_OUTPUT
            fi
          done
      - name: Install package and streaming extractor dependencies
        if: ${{ steps.modules-changed.outputs.STREAMING_CHANGED == 'true' }}
        run: pip install -e .[test_core,streaming_extractors]
      # Temporary disabled because of complicated error with path
      # - name: Install h5py with ROS3 support and test it works
      #   run: |
      #     pip uninstall -y h5py
      #     conda install -c conda-forge "h5py>=3.2"
      #     python -c "import h5py; assert 'ros3' in h5py.registered_drivers(), f'ros3 suppport not available, failed to install'"
      - name: run tests
        if: steps.modules-changed.outputs.STREAMING_CHANGED == 'true'
        run: pytest -m "streaming_extractors and not ros3_test" -vv -ra
