name: Profile Imports

on:
  pull_request:
    types: [synchronize, opened, reopened]
    branches:
      - main

concurrency:  # Cancel previous workflows on the same pull request
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  test-and-profile-main-imports:
    name: Profile imports on ${{ matrix.os }} OS
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Spikeinterface with only core dependencies
        run: |
          git config --global user.email "CI@example.com"
          git config --global user.name "CI Almighty"
          python -m pip install -U pip  # Official recommended way
          pip install .  # This should install core only
      - name: Profile Imports
        run: |
          echo "## OS: ${{ matrix.os }}" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "### Import times when only installing only core dependencies " >> $GITHUB_STEP_SUMMARY
          python ./.github/import_test.py >> $GITHUB_STEP_SUMMARY
        shell: bash  # Necessary for pipeline to work on windows
      - name: Install in full mode
        run: |
          pip install .[full]
      - name: Profile Imports with full
        run: |
          # Add a header to separate the two profiles
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "### Import times when installing full dependencies in " >> $GITHUB_STEP_SUMMARY
          python ./.github/import_test.py >> $GITHUB_STEP_SUMMARY
        shell: bash  # Necessary for pipeline to work on windows
